//go:build !gpui_native_noembed

package native

import _ "embed"

// The exact default artifact: one DLL and one authoritative manifest, embedded
// at build time from internal/native/artifacts/ (generated by
// `go run ./reference/native/tools/measure` after `cargo build --release -p
// gpui-go-native`). Consumers never need Rust: these bytes are the artifact.
//
// The build tag gpui_native_noembed swaps this file for a stub. It exists only
// to measure the embedding's contribution to module/binary size; a noembed
// build has no default artifact and requires a bundle.
var (
	//go:embed artifacts/gpui_go_native.dll
	embeddedDLL []byte

	//go:embed artifacts/manifest.json
	embeddedManifest []byte
)
