package native

import (
	"encoding/json"
	"fmt"
	"strconv"
)

// Manifest is the exact artifact identity record embedded with (and shipped
// beside) the DLL. It is generated by `go run ./reference/native/tools/measure`
// from the real build; see reference/README.md for the field documentation.
//
// The manifest embedded in this Go package is the *authoritative* identity for
// the release: a bundle-local manifest can never authorize a replacement hash
// or identity (distribution contract).
type Manifest struct {
	Schema             string   `json:"schema"`
	Name               string   `json:"name"`
	SHA256             string   `json:"sha256"`
	Bytes              int64    `json:"bytes"`
	GzipBytes          int64    `json:"gzip_bytes"`
	GzipSHA256         string   `json:"gzip_sha256"`
	CECommit           string   `json:"ce_commit"`
	ABIVersion         uint32   `json:"abi_version"`
	NativeRevision     uint32   `json:"native_revision"`
	CapabilitiesMask   uint64   `json:"capabilities_mask"`
	Capabilities       []string `json:"capabilities"`
	Target             string   `json:"target"`
	Machine            string   `json:"machine"`
	BuiltAt            string   `json:"built_at"`
	Rustc              string   `json:"rustc"`
	CRTStaticRequested bool     `json:"crt_static_requested"`
	CRTStaticOutcome   string   `json:"crt_static_outcome"`
	Imports            []string `json:"imports"`
	Provenance         string   `json:"provenance"`
	// Taffy records the resolved layout engine of the layout service
	// (ticket06; empty/nil for artifacts without the layout capability).
	// Provenance only — matchesAuthority compares identity fields above.
	Taffy *TaffyResolution `json:"taffy,omitempty"`
	// Windows records the resolved windows crate family of the renderer
	// service (ticket07; empty/nil for artifacts without the renderer
	// capability). Provenance only.
	Windows *WindowsResolution `json:"windows,omitempty"`
	// Text records the resolved Parley text stack of the text service
	// (ticket09; empty/nil for artifacts without the text capability).
	// Provenance only.
	Text *TextResolution `json:"text,omitempty"`
	// Glyph records the resolved glyph/atlas stack of the raster and
	// atlas services (ticket10; empty/nil for artifacts without the
	// glyph/atlas capabilities). Provenance only.
	Glyph *GlyphResolution `json:"glyph,omitempty"`
}

// TaffyResolution is the resolved Taffy engine of the native layout service,
// as recorded by the measurement tool from the workspace lock and cargo
// tree.
type TaffyResolution struct {
	Version      string   `json:"version"`
	Checksum     string   `json:"checksum"`
	PinSatisfied bool     `json:"version_pin_satisfied"`
	Features     []string `json:"default_features"`
	FeatureGraph string   `json:"feature_graph"`
	Deps         []string `json:"dependencies"`
}

// WindowsResolution is the resolved windows crate family of the native
// renderer service, as recorded by the measurement tool from the workspace
// lock and cargo tree (ticket07).
type WindowsResolution struct {
	Version      string   `json:"version"`
	Checksum     string   `json:"checksum"`
	PinSatisfied bool     `json:"version_pin_satisfied"`
	Features     []string `json:"features"`
	FeatureGraph string   `json:"feature_graph"`
	Deps         []string `json:"dependencies"`
}

// TextResolution is the resolved Parley text stack of the native text
// service, as recorded by the measurement tool from the workspace lock
// and cargo tree (ticket09): the registry versions of
// parley/fontique/harfrust/skrifa/swash plus the pinned source-path
// crates gpui-ce/gpui_ce_parley.
type TextResolution struct {
	Parley       TextCrateResolution `json:"parley"`
	Fontique     TextCrateResolution `json:"fontique"`
	Harfrust     TextCrateResolution `json:"harfrust"`
	Skrifa       TextCrateResolution `json:"skrifa"`
	Swash        TextCrateResolution `json:"swash"`
	GpuiCe       TextPathResolution  `json:"gpui_ce"`
	GpuiCeParley TextPathResolution  `json:"gpui_ce_parley"`
	FeatureGraph string              `json:"feature_graph"`
}

// TextCrateResolution is one registry crate of the text stack.
type TextCrateResolution struct {
	Version      string `json:"version"`
	Checksum     string `json:"checksum"`
	PinSatisfied bool   `json:"version_pin_satisfied"`
}

// TextPathResolution is one pinned source-path crate of the text stack.
type TextPathResolution struct {
	Version string   `json:"version"`
	Path    string   `json:"path"`
	Deps    []string `json:"dependencies"`
}

// GlyphResolution is the resolved glyph/atlas stack of the native raster
// and atlas services, as recorded by the measurement tool from the
// workspace lock and cargo tree (ticket10): etagere (the pinned atlas
// packing algorithm), windows-numerics (the rasterizer's Vector2) and
// anyhow (the ported rasterizer's error type).
type GlyphResolution struct {
	Etagere         TextCrateResolution `json:"etagere"`
	WindowsNumerics TextCrateResolution `json:"windows_numerics"`
	Anyhow          TextCrateResolution `json:"anyhow"`
	FeatureGraph    string              `json:"feature_graph"`
}

// parseManifest decodes and sanity-checks a manifest record.
func parseManifest(data []byte) (*Manifest, error) {
	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return nil, fmt.Errorf("native: parsing manifest: %w", err)
	}
	if len(m.SHA256) != 64 || !isLowerHex(m.SHA256) {
		return nil, fmt.Errorf("native: manifest sha256 field malformed: %q", m.SHA256)
	}
	if m.Name == "" || m.Bytes <= 0 || m.ABIVersion == 0 || m.CECommit == "" {
		return nil, fmt.Errorf("native: manifest missing required identity fields")
	}
	return &m, nil
}

// isLowerHex reports whether s consists only of lowercase hex digits
// (sha256.HexEncode output).
func isLowerHex(s string) bool {
	for i := 0; i < len(s); i++ {
		c := s[i]
		if !('0' <= c && c <= '9') && !('a' <= c && c <= 'f') {
			return false
		}
	}
	return true
}

// matchesAuthority checks that a candidate manifest agrees with the embedded
// authoritative manifest on every identity field: exact DLL hash and size, ABI
// version, native revision, CE pin, capability mask and target. Any
// disagreement means the bundle is trying to authorize a different artifact.
func (m *Manifest) matchesAuthority(auth *Manifest) error {
	type field struct {
		name, want, got string
	}
	checks := []field{
		{"sha256", auth.SHA256, m.SHA256},
		{"bytes", strconv.FormatInt(auth.Bytes, 10), strconv.FormatInt(m.Bytes, 10)},
		{"abi_version", strconv.FormatUint(uint64(auth.ABIVersion), 10), strconv.FormatUint(uint64(m.ABIVersion), 10)},
		{"native_revision", strconv.FormatUint(uint64(auth.NativeRevision), 10), strconv.FormatUint(uint64(m.NativeRevision), 10)},
		{"ce_commit", auth.CECommit, m.CECommit},
		{"capabilities_mask", fmt.Sprintf("%#x", auth.CapabilitiesMask), fmt.Sprintf("%#x", m.CapabilitiesMask)},
		{"target", auth.Target, m.Target},
	}
	for _, c := range checks {
		if c.want != c.got {
			return fmt.Errorf("%w: field %s: embedded authoritative manifest says %q, bundle manifest says %q",
				ErrBundleManifest, c.name, c.want, c.got)
		}
	}
	return nil
}
