package gpui

// This file ports the keystroke vocabulary of the pinned CE reference
// 254b5dbd47cbb5acbcc5bbdcbb322a339276c88a:
//
//   - crates/gpui/src/platform/keystroke.rs — Keystroke, Modifiers,
//     KeybindingKeystroke (with the Windows display key/modifiers),
//     Keystroke::parse (the [secondary-][ctrl-][alt-][shift-][cmd-][fn-]
//     key[->key_char] grammar), unparse, should_match (the Windows
//     branch: a typed key_char matches a binding with no modifiers),
//     is_ime_in_progress and with_simulated_ime;
//   - crates/gpui/src/interactive.rs — ModifiersChangedEvent;
//   - crates/gpui/src/platform.rs — the platform input event shapes the
//     keyboard path consumes (KeyDownEvent, KeyUpEvent).
//
// Deliberate Go adaptations, recorded beside the behavior they alter:
//
//   - The reference's Option<String> key_char becomes a plain string
//     where "" is "none". The parse grammar cannot produce an empty
//     key_char (the "->key_char" arm requires a non-empty suffix) and
//     every platform producer filters empty strings, so the collapsed
//     representation is unambiguous.
//
//   - The Windows-specific KeybindingKeystroke display fields are
//     unconditional in the port (the reference cfg-gates them); this
//     port targets Windows, and the non-Windows build keeps the fields
//     inert behind the same accessor semantics.

import (
	"fmt"
	"strings"
)

// ---------------------------------------------------------------------------
// Modifiers
// ---------------------------------------------------------------------------

// Modifiers is the state of the modifier keys at some point in time
// (platform/keystroke.rs Modifiers).
type Modifiers struct {
	// Control is the control key.
	Control bool
	// Alt is the alt key, sometimes also known as the 'meta' key.
	Alt bool
	// Shift is the shift key.
	Shift bool
	// Platform is the command key on macOS, the windows key on Windows,
	// the super key on Linux.
	Platform bool
	// Function is the function key.
	Function bool
}

// Modified reports whether any modifier key is pressed.
func (m Modifiers) Modified() bool {
	return m.Control || m.Alt || m.Shift || m.Platform || m.Function
}

// Secondary reports whether the semantically 'secondary' modifier key
// is pressed: the command key on macOS, the control key on Linux and
// Windows.
func (m Modifiers) Secondary() bool { return m.Control }

// NumberOfModifiers reports how many modifier keys are pressed.
func (m Modifiers) NumberOfModifiers() uint8 {
	count := uint8(0)
	if m.Control {
		count++
	}
	if m.Alt {
		count++
	}
	if m.Shift {
		count++
	}
	if m.Platform {
		count++
	}
	if m.Function {
		count++
	}
	return count
}

// IsSubsetOf reports whether every modifier pressed in m is also
// pressed in other.
func (m Modifiers) IsSubsetOf(other Modifiers) bool {
	return (!m.Control || other.Control) &&
		(!m.Alt || other.Alt) &&
		(!m.Shift || other.Shift) &&
		(!m.Platform || other.Platform) &&
		(!m.Function || other.Function)
}

// NoModifiers returns Modifiers with no modifiers (Modifiers::none).
func NoModifiers() Modifiers { return Modifiers{} }

// ControlModifiers returns Modifiers with just control.
func ControlModifiers() Modifiers { return Modifiers{Control: true} }

// AltModifiers returns Modifiers with just alt.
func AltModifiers() Modifiers { return Modifiers{Alt: true} }

// ShiftModifiers returns Modifiers with just shift.
func ShiftModifiers() Modifiers { return Modifiers{Shift: true} }

// PlatformModifiers returns Modifiers with just the platform key.
func PlatformModifiers() Modifiers { return Modifiers{Platform: true} }

// FunctionModifiers returns Modifiers with just function.
func FunctionModifiers() Modifiers { return Modifiers{Function: true} }

// ControlShiftModifiers returns Modifiers with control + shift.
func ControlShiftModifiers() Modifiers { return Modifiers{Control: true, Shift: true} }

// SecondaryModifiers returns Modifiers with just the secondary key
// (control on Windows).
func SecondaryModifiers() Modifiers { return ControlModifiers() }

// Capslock is the state of the capslock key at some point in time.
type Capslock struct {
	// On reports whether the capslock key is on.
	On bool
}

// ---------------------------------------------------------------------------
// Keystroke
// ---------------------------------------------------------------------------

// Keystroke is a keystroke and associated metadata generated by the
// platform (platform/keystroke.rs Keystroke).
type Keystroke struct {
	// Modifiers is the state of the modifier keys at the time the
	// keystroke was generated.
	Modifiers Modifiers

	// Key is the character printed on the key that was pressed, e.g.
	// for option-s the key is "s". On layouts that do not have ASCII
	// keys (e.g. Thai) this is the ASCII-equivalent character (q
	// instead of ๆ), and the typed character is present in KeyChar.
	Key string

	// KeyChar is the character that could have been typed when this
	// binding was pressed, e.g. for s this is "s", for option-s "ß",
	// and for cmd-s "" (none in the reference).
	KeyChar string
}

// KEYSTROKE_PARSE_EXPECTED_MESSAGE is the sentence explaining what the
// keystroke parser expects, starting with "Expected ...".
const KEYSTROKE_PARSE_EXPECTED_MESSAGE = "Expected a sequence of modifiers " +
	"(`ctrl`, `alt`, `shift`, `fn`, `cmd`, `super`, or `win`) " +
	"followed by a key, separated by `-`."

// InvalidKeystrokeError reports a rejected keystroke parse
// (InvalidKeystrokeError in the reference).
type InvalidKeystrokeError struct {
	// Keystroke is the invalid source text.
	Keystroke string
}

func (e *InvalidKeystrokeError) Error() string {
	return fmt.Sprintf("Invalid keystroke %q. %s", e.Keystroke, KEYSTROKE_PARSE_EXPECTED_MESSAGE)
}

// ShouldMatch reports whether this typed keystroke matches the given
// keybinding keystroke.
//
// When matching a key we cannot know whether the user intended to type
// the KeyChar or the Key itself. On some non-US keyboards keys used in
// bindings are behind option (for example `$` is typed alt-ç on a Czech
// keyboard), and on some keyboards the IME handler converts a sequence
// of keys into a specific character.
//
// This method assumes that this keystroke was typed and target is in
// the keymap, and checks both possibilities for this against the
// target. On Windows, if key_char is set then the typed keystroke
// produced the key_char, so a binding with no modifiers and the
// key_char as its key matches (should_match's #[cfg(target_os =
// "windows")] branch).
func (k Keystroke) ShouldMatch(target *KeybindingKeystroke) bool {
	if k.KeyChar != "" && k.KeyChar != k.Key {
		if target.inner.Key == k.KeyChar && target.inner.Modifiers == (Modifiers{}) {
			return true
		}
	}
	return target.inner.Modifiers == k.Modifiers && target.inner.Key == k.Key
}

// ParseKeystroke parses a keystroke from the reference's key syntax:
//
//	[secondary-][ctrl-][alt-][shift-][cmd-][fn-]key[->key_char]
//
// key_char syntax is only used for generating test events; secondary
// means "cmd" on macOS and "ctrl" on other platforms; a key with a
// key_char set is matched without it. A single ASCII uppercase key is
// converted to shift plus the lowercase character; named keys like
// "tab" and "enter" are accepted case-insensitively. A keystroke that
// is only a modifier ("ctrl", "shift", ...) resolves to that modifier
// as the key with the modifier flag cleared.
//
// The reference accepts an empty source as a keystroke with an empty
// key (Keystroke::parse("") yields key: ""); the port preserves that
// quirk because is_ime_in_progress tests for it.
func ParseKeystroke(source string) (Keystroke, error) {
	var modifiers Modifiers
	var key string
	var keyChar string
	haveKey := false

	components := strings.Split(source, "-")
	i := 0
	for i < len(components) {
		component := components[i]
		i++

		if strings.EqualFold(component, "ctrl") {
			modifiers.Control = true
			continue
		}
		if strings.EqualFold(component, "alt") {
			modifiers.Alt = true
			continue
		}
		if strings.EqualFold(component, "shift") {
			modifiers.Shift = true
			continue
		}
		if strings.EqualFold(component, "fn") {
			modifiers.Function = true
			continue
		}
		if strings.EqualFold(component, "secondary") {
			// secondary means "cmd" on macOS and "ctrl" on other
			// platforms (Windows: control).
			modifiers.Control = true
			continue
		}
		if strings.EqualFold(component, "cmd") ||
			strings.EqualFold(component, "super") ||
			strings.EqualFold(component, "win") {
			modifiers.Platform = true
			continue
		}

		keyStr := component

		if i < len(components) {
			next := components[i]
			if next == "" && strings.HasSuffix(source, "-") {
				key = "-"
				haveKey = true
				break
			} else if len(next) > 1 && strings.HasPrefix(next, ">") {
				key = keyStr
				haveKey = true
				// The key_char is next[1:]: the parse grammar requires a
				// non-empty suffix, so an empty key_char cannot appear
				// here.
				keyChar = next[1:]
				i++
			} else {
				return Keystroke{}, &InvalidKeystrokeError{Keystroke: source}
			}
			continue
		}

		if len(component) == 1 && component[0] >= 'A' && component[0] <= 'Z' {
			// Convert to shift + lowercase char.
			modifiers.Shift = true
			keyStr = strings.ToLower(component)
		} else {
			// Convert ASCII characters to lowercase so named keys like
			// "tab" and "enter" are accepted case insensitively and
			// stored how we expect so they are matched properly.
			keyStr = strings.ToLower(component)
		}
		key = keyStr
		haveKey = true
	}

	// Allow for the user to specify a keystroke modifier as the key
	// itself. This sets the key to the modifier, and disables the
	// modifier.
	if !haveKey {
		switch {
		case modifiers.Shift:
			modifiers.Shift = false
			key = "shift"
		case modifiers.Control:
			modifiers.Control = false
			key = "control"
		case modifiers.Alt:
			modifiers.Alt = false
			key = "alt"
		case modifiers.Platform:
			modifiers.Platform = false
			key = "platform"
		case modifiers.Function:
			modifiers.Function = false
			key = "function"
		}
	}

	return Keystroke{Modifiers: modifiers, Key: key, KeyChar: keyChar}, nil
}

// MustParseKeystroke parses a keystroke, panicking on failure. It is
// the test/fixture spelling of ParseKeystroke.
func MustParseKeystroke(source string) Keystroke {
	keystroke, err := ParseKeystroke(source)
	if err != nil {
		panic(err)
	}
	return keystroke
}

// Unparse produces a representation of this key that ParseKeystroke can
// understand.
func (k Keystroke) Unparse() string {
	var b strings.Builder
	if k.Modifiers.Function {
		b.WriteString("fn-")
	}
	if k.Modifiers.Control {
		b.WriteString("ctrl-")
	}
	if k.Modifiers.Alt {
		b.WriteString("alt-")
	}
	if k.Modifiers.Platform {
		// On Windows the platform modifier unparses as "win-" (unparse
		// in platform/keystroke.rs).
		b.WriteString("win-")
	}
	if k.Modifiers.Shift {
		b.WriteString("shift-")
	}
	b.WriteString(k.Key)
	return b.String()
}

// String renders the keystroke as its parse-compatible representation
// (the reference's Display uses platform-specific glyphs for the UI;
// the port keeps the round-trippable spelling and defers the glyph
// rendering to a later UI slice).
func (k Keystroke) String() string { return k.Unparse() }

// IsIMEInProgress reports whether this keystroke left the IME system in
// an incomplete state.
func (k Keystroke) IsIMEInProgress() bool {
	return k.KeyChar == "" &&
		(isPrintableKey(k.Key) || k.Key == "") &&
		!(k.Modifiers.Platform || k.Modifiers.Control || k.Modifiers.Function || k.Modifiers.Alt)
}

// WithSimulatedIME returns a new keystroke with the KeyChar filled.
// This is used for dispatch_keystroke where we want users to be able to
// simulate typing "space", etc.
func (k Keystroke) WithSimulatedIME() Keystroke {
	if k.KeyChar == "" &&
		!k.Modifiers.Platform &&
		!k.Modifiers.Control &&
		!k.Modifiers.Function &&
		!k.Modifiers.Alt {
		switch k.Key {
		case "space":
			k.KeyChar = " "
		case "tab":
			k.KeyChar = "\t"
		case "enter":
			k.KeyChar = "\n"
		default:
			if isPrintableKey(k.Key) && k.Key != "" {
				if k.Modifiers.Shift {
					k.KeyChar = strings.ToUpper(k.Key)
				} else {
					k.KeyChar = k.Key
				}
			}
		}
	}
	return k
}

// isPrintableKey reports whether the key name can produce text input
// (is_printable_key in platform/keystroke.rs).
func isPrintableKey(key string) bool {
	switch key {
	case "f1", "f2", "f3", "f4", "f5", "f6", "f7", "f8", "f9", "f10",
		"f11", "f12", "f13", "f14", "f15", "f16", "f17", "f18", "f19",
		"f20", "f21", "f22", "f23", "f24", "f25", "f26", "f27", "f28",
		"f29", "f30", "f31", "f32", "f33", "f34", "f35",
		"backspace", "delete", "left", "right", "up", "down",
		"pageup", "pagedown", "insert", "home", "end",
		"back", "forward", "escape":
		return false
	}
	return true
}

// ---------------------------------------------------------------------------
// KeybindingKeystroke
// ---------------------------------------------------------------------------

// KeybindingKeystroke represents a keystroke that can be used in
// keybindings and displayed to the user (platform/keystroke.rs
// KeybindingKeystroke). On Windows it carries a display key and display
// modifiers alongside the GPUI representation: a ctrl-@ keystroke has
// inner.modifiers as control and display modifiers as control-shift,
// inner.key as @ and display key as 2.
type KeybindingKeystroke struct {
	// inner is the GPUI representation of the keystroke.
	inner Keystroke
	// displayModifiers are the modifiers to display (Windows).
	displayModifiers Modifiers
	// displayKey is the key to display (Windows).
	displayKey string
}

// NewKeybindingKeystroke creates a keybinding keystroke from the given
// keystroke, without any platform-specific mapping
// (KeybindingKeystroke::from_keystroke).
func NewKeybindingKeystroke(inner Keystroke) KeybindingKeystroke {
	return KeybindingKeystroke{
		inner:            inner,
		displayModifiers: inner.Modifiers,
		displayKey:       inner.Key,
	}
}

// NewKeybindingKeystrokeWithDisplay creates a keybinding keystroke with
// explicit Windows display fields (KeybindingKeystroke::new).
func NewKeybindingKeystrokeWithDisplay(inner Keystroke, displayModifiers Modifiers, displayKey string) KeybindingKeystroke {
	return KeybindingKeystroke{inner: inner, displayModifiers: displayModifiers, displayKey: displayKey}
}

// Inner returns the GPUI representation of the keystroke.
func (k KeybindingKeystroke) Inner() Keystroke { return k.inner }

// Modifiers returns the modifiers to display.
func (k KeybindingKeystroke) Modifiers() Modifiers { return k.displayModifiers }

// Key returns the key to display.
func (k KeybindingKeystroke) Key() string { return k.displayKey }

// SetModifiers sets the modifiers. On Windows this modifies both the
// inner and the display modifiers.
func (k *KeybindingKeystroke) SetModifiers(modifiers Modifiers) {
	k.inner.Modifiers = modifiers
	k.displayModifiers = modifiers
}

// SetKey sets the key. On Windows this modifies both the inner and the
// display keys.
func (k *KeybindingKeystroke) SetKey(key string) {
	k.displayKey = key
	k.inner.Key = key
}

// Unparse produces a representation of this key that ParseKeystroke can
// understand (the Windows display spelling).
func (k KeybindingKeystroke) Unparse() string {
	var b strings.Builder
	if k.displayModifiers.Function {
		b.WriteString("fn-")
	}
	if k.displayModifiers.Control {
		b.WriteString("ctrl-")
	}
	if k.displayModifiers.Alt {
		b.WriteString("alt-")
	}
	if k.displayModifiers.Platform {
		b.WriteString("win-")
	}
	if k.displayModifiers.Shift {
		b.WriteString("shift-")
	}
	b.WriteString(k.displayKey)
	return b.String()
}

// RemoveKeyChar removes the key_char.
func (k *KeybindingKeystroke) RemoveKeyChar() { k.inner.KeyChar = "" }

// String renders the display spelling.
func (k KeybindingKeystroke) String() string { return k.Unparse() }

// matchKeystrokes checks if the given keystrokes match this binding.
// It reports whether the keystrokes match at all, and whether more
// keystrokes are still required to complete the binding (Option<bool>
// in the reference: no match, a prefix, or a full match).
func (k *KeybindingKeystroke) matchKeystrokes(typed []Keystroke) (matched bool, pending bool) {
	binding := []KeybindingKeystroke{*k}
	if len(binding) < len(typed) {
		return false, false
	}
	for i := range typed {
		if !typed[i].ShouldMatch(&binding[i]) {
			return false, false
		}
	}
	return true, len(binding) > len(typed)
}

// ---------------------------------------------------------------------------
// Keyboard input events
// ---------------------------------------------------------------------------

// KeyDownEvent is a key down platform event (platform.rs KeyDownEvent).
type KeyDownEvent struct {
	// Keystroke is the key that was pressed.
	Keystroke Keystroke
	// IsHeld reports whether the key is auto-repeating (the Windows
	// repeat bit of WM_KEYDOWN's lparam).
	IsHeld bool
	// PreferCharacterInput reports that the platform prefers text input
	// over a key binding for this keystroke (dead keys and
	// layout-dependent AltGr characters set this on Windows).
	PreferCharacterInput bool
}

// KeyUpEvent is a key up platform event (platform.rs KeyUpEvent).
type KeyUpEvent struct {
	// Keystroke is the key that was released.
	Keystroke Keystroke
}

// ModifiersChangedEvent is a change of the keyboard modifier state
// (interactive.rs ModifiersChangedEvent).
type ModifiersChangedEvent struct {
	// Modifiers is the new state of the modifier keys.
	Modifiers Modifiers
	// Capslock is the state of the capslock key.
	Capslock Capslock
}

// PlatformInput is the keyboard platform input the window dispatch
// consumes (the keyboard members of platform.rs PlatformInput). Mouse,
// touch and IME composition inputs arrive with their tickets.
type PlatformInput interface {
	platformInput()
}

func (*KeyDownEvent) platformInput()          {}
func (*KeyUpEvent) platformInput()            {}
func (*ModifiersChangedEvent) platformInput() {}

// ---------------------------------------------------------------------------
// Keyboard mapper
// ---------------------------------------------------------------------------

// KeyboardMapper maps a parsed keystroke into its keybinding form
// (PlatformKeyboardMapper in the reference). MapKeyEquivalent is the
// seam a platform uses to translate user-facing bindings through the
// actual keyboard layout.
type KeyboardMapper interface {
	// MapKeyEquivalent maps the keystroke, using key equivalents from a
	// US layout when useKeyEquivalents is set.
	MapKeyEquivalent(keystroke Keystroke, useKeyEquivalents bool) KeybindingKeystroke
}

// DummyKeyboardMapper is the identity mapper (DummyKeyboardMapper in
// the reference): bindings keep exactly the keystroke the author wrote.
type DummyKeyboardMapper struct{}

// MapKeyEquivalent implements KeyboardMapper.
func (DummyKeyboardMapper) MapKeyEquivalent(keystroke Keystroke, _ bool) KeybindingKeystroke {
	return NewKeybindingKeystroke(keystroke)
}
